# Generated by ProjektZAI 5.2.1 on 2025-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('INPR', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
